# Numpy

Website: https://youtu.be/4PXAztQtoTg?t=3157

In [16]:
import numpy as np

### Generating array 

In [9]:
#setting a random seed for reproducibility 
rnd = np.random.RandomState(seed = 123)

#Generating a random array 
X = rnd.uniform(low = 0.0, high = 1.0, size = (3,5)) # a 3 x 5 array 

print(X)
X #Shows you what type of object is 

[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
 [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]]


array([[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897],
       [0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752],
       [0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426]])

In [10]:
print(X.shape)
print(X.dtype)

(3, 5)
float64


### Indexing, Slicing

In [11]:
#Acessing elements 
#get a single element 
#( here: an element in the first row and columns)
print(X[1,0])

0.42310646012446096


In [12]:
#get a row 
# (here: 2nd row)
print(X[1])

[0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]


In [13]:
#get a column 
#here 2nd column
print(X[:,1])

[0.28613933 0.9807642  0.72904971]


In [15]:
#Transposing an array
print(X.T)

[[0.69646919 0.42310646 0.34317802]
 [0.28613933 0.9807642  0.72904971]
 [0.22685145 0.68482974 0.43857224]
 [0.55131477 0.4809319  0.0596779 ]
 [0.71946897 0.39211752 0.39804426]]


In [18]:
#creating a row vector 
#of evenly spaced numbers over a specified interval. 
y = np.linspace(0, 12, 5)
y

array([ 0.,  3.,  6.,  9., 12.])

In [20]:
#turning row vector into column vector 
y[:, np.newaxis]


array([[ 0.],
       [ 3.],
       [ 6.],
       [ 9.],
       [12.]])

Why would you need np.newaxis: might come in handy when you want to explicitly convert a 1D array to either 
    a row vector or a column vector, as depicted in the above picture.
    
   Stackoverflow explains other possible scenarios when this is useful: https://stackoverflow.com/questions/29241056/how-does-numpy-newaxis-work-and-when-to-use-it

### Reshaping an array

In [24]:
#Getting the shape or reshaping an array 

rnd = np.random.RandomState(seed = 123)
X = rnd.uniform(low = 0.0, high = 1., size = (3, 5)) # a 3x5 array 
print(X.shape)
print(X)

(3, 5)
[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
 [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]]


In [25]:
# reshape X to be size of (3,5)
X_reshaped = X.reshape(5,3) #new dimension numbers must match old dimension numbers
X_reshaped

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426]])

 #### Note: Reshaping maintains the internal order of the data

In [34]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
#reshape must include numbers of multiple 12
#notice that the numbers still go from 0 to 12
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
print(X)

[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
 [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]]


In [39]:
#Fancy indexing - in this case we extracted columns 3, 1, 0 in that order 
indices = np.array([3,1,0])
print(indices)
X[:, indices]

[3 1 0]


array([[0.55131477, 0.28613933, 0.69646919],
       [0.4809319 , 0.9807642 , 0.42310646],
       [0.0596779 , 0.72904971, 0.34317802]])